// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBik1Ma8WmR_USs-KvAeIOQ9Z1rEV4nVT8',
    appId: '1:630293463384:web:367e0e6ce5a6b95b6ce52d',
    messagingSenderId: '630293463384',
    projectId: 'wasteagram-6869c',
    authDomain: 'wasteagram-6869c.firebaseapp.com',
    storageBucket: 'wasteagram-6869c.appspot.com',
    measurementId: 'G-CG4LQKS147',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAJDB_FSU9TUL8C2LuLoP0RtNleB7C4Kg',
    appId: '1:630293463384:android:d69517870088c44b6ce52d',
    messagingSenderId: '630293463384',
    projectId: 'wasteagram-6869c',
    storageBucket: 'wasteagram-6869c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYX4j0bxDoQvUnAqjQS1s_1zVqj5QLIQ0',
    appId: '1:630293463384:ios:f967af11396741736ce52d',
    messagingSenderId: '630293463384',
    projectId: 'wasteagram-6869c',
    storageBucket: 'wasteagram-6869c.appspot.com',
    iosClientId: '630293463384-88446rlpi864iojsfd5ci2hvfvp0old6.apps.googleusercontent.com',
    iosBundleId: 'edu.oregonstate.rameshsa.wasteagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYX4j0bxDoQvUnAqjQS1s_1zVqj5QLIQ0',
    appId: '1:630293463384:ios:f967af11396741736ce52d',
    messagingSenderId: '630293463384',
    projectId: 'wasteagram-6869c',
    storageBucket: 'wasteagram-6869c.appspot.com',
    iosClientId: '630293463384-88446rlpi864iojsfd5ci2hvfvp0old6.apps.googleusercontent.com',
    iosBundleId: 'edu.oregonstate.rameshsa.wasteagram',
  );
}
