name: wasteagram
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  firebase_analytics: ^9.3.1
  intl: ^0.17.0
  location: ^4.4.0
  grpc: ^3.0.2
  cloud_firestore: ^3.4.4
  firebase_core: ^1.4.0  
  firebase_storage: ^10.0.1
  image_picker: ^0.8.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  testing: ^0.0.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.16.0
  sentry_flutter: ^6.9.0
flutter:
  uses-material-design: true