name: journal
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  cupertino_icons: ^1.0.2
  shared_preferences: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl: any

flutter:
  uses-material-design: true
  assets:
   - assets/create_sql_table.txt
    